#!/bin/sh
adb shell pm uninstall --user 0 com.android.calendar
adb shell pm uninstall --user 0 com.android.chrome 
adb shell pm uninstall --user 0 com.android.mms
adb shell pm uninstall --user 0 com.autonavi.minimap
adb shell pm uninstall --user 0 com.baidu.duersdk.opensdk
adb shell pm uninstall --user 0 com.baidu.input_mi
adb shell pm uninstall --user 0 com.baidu.searchbox
adb shell pm uninstall --user 0 com.caf.fmradio
adb shell pm uninstall --user 0 com.duokan.phone.remotecontroller
adb shell pm uninstall --user 0 com.facebook.katana
adb shell pm uninstall --user 0 com.google.android.apps.docs
adb shell pm uninstall --user 0 com.google.android.apps.maps
adb shell pm uninstall --user 0 com.google.android.marvin.talkback
adb shell pm uninstall --user 0 com.google.android.talk
adb shell pm uninstall --user 0 com.google.android.tts
adb shell pm uninstall --user 0 com.google.android.youtube
adb shell pm uninstall --user 0 com.mi.android.globalFileexplorer
adb shell pm uninstall --user 0 com.mi.android.globalpersonalassistant
adb shell pm uninstall --user 0 com.milink.service
adb shell pm uninstall --user 0 com.mi.liveassistant
adb shell pm uninstall --user 0 com.mipay.wallet
adb shell pm uninstall --user 0 com.miui.android.fashiongallery
adb shell pm uninstall --user 0 com.miui.antispam
adb shell pm uninstall --user 0 com.miui.calculator
adb shell pm uninstall --user 0 com.miui.cleanmaster
adb shell pm uninstall --user 0 com.miui.cloudservice.sysbase
adb shell pm uninstall --user 0 com.miui.contentcatcher
adb shell pm uninstall --user 0 com.miui.daemon
adb shell pm uninstall --user 0 com.miui.fm
adb shell pm uninstall --user 0 com.miui.home
adb shell pm uninstall --user 0 com.miui.klo.bugreport
adb shell pm uninstall --user 0 com.miui.msa.global
adb shell pm uninstall --user 0 com.miui.personalassistant
adb shell pm uninstall --user 0 com.miui.providers.weather
adb shell pm uninstall --user 0 com.miui.systemAdSolution
adb shell pm uninstall --user 0 com.miui.translation.kingsoft
adb shell pm uninstall --user 0 com.miui.translation.youdao
adb shell pm uninstall --user 0 com.miui.video
adb shell pm uninstall --user 0 com.miui.videoplayer.overlay
adb shell pm uninstall --user 0 com.miui.virtualsim
adb shell pm uninstall --user 0 com.miui.vsimcore
adb shell pm uninstall --user 0 com.miui.weather2
adb shell pm uninstall --user 0 com.miui.yellowpage
adb shell pm uninstall --user 0 com.mi.webkit.core
adb shell pm uninstall --user 0 com.qiyi.video
adb shell pm uninstall --user 0 com.sohu.inputmethod.sogou.xiaomi
adb shell pm uninstall --user 0 com.xiaomi.ab
adb shell pm uninstall --user 0 com.xiaomi.account
adb shell pm uninstall --user 0 com.xiaomi.channel
adb shell pm uninstall --user 0 com.xiaomi.gamecenter.sdk.service
adb shell pm uninstall --user 0 com.xiaomi.joyose
adb shell pm uninstall --user 0 com.xiaomi.jr
adb shell pm uninstall --user 0 com.xiaomi.lens
adb shell pm uninstall --user 0 com.xiaomi.midrop.overlay
adb shell pm uninstall --user 0 com.xiaomi.pass
adb shell pm uninstall --user 0 com.xiaomi.shop
adb shell pm uninstall --user 0 com.xiaomi.vipaccount
