#!/bin/sh
adb shell pm uninstall --user 0 com.samsung.android.messaging
adb shell pm uninstall --user 0 com.sec.android.inputmethod
adb shell pm uninstall --user 0 com.sec.android.app.myfiles
adb shell pm uninstall --user 0 com.sec.android.app.sbrowser
adb shell pm uninstall --user 0 com.samsung.android.app.spage
adb shell pm uninstall --user 0 com.samsung.android.visionintelligence
adb shell pm uninstall --user 0 com.samsung.android.bixby.agent
adb shell pm uninstall --user 0 com.samsung.android.bixby.es.globalaction
adb shell pm uninstall --user 0 com.samsung.android.bixbyvision.framework
adb shell pm uninstall --user 0 com.samsung.android.bixby.agent.dummy 
adb shell pm uninstall --user 0 com.samsung.android.visioncloudagent
adb shell pm uninstall --user 0 com.samsung.visionprovider
adb shell pm uninstall --user 0 com.samsung.android.bixby.wakeup
adb shell pm uninstall --user 0 com.samsung.android.bixby.voiceinput
adb shell pm uninstall --user 0 com.samsung.aasaservice
adb shell pm uninstall --user 0 com.sec.android.AutoPreconfig
adb shell pm uninstall --user 0 com.samsung.android.bbc.bbcagent
adb shell pm uninstall --user 0 flipboard.boxer.app
adb shell pm uninstall --user 0 com.samsung.android.drivelink.stub
adb shell pm uninstall --user 0 com.monotype.android.font.chococooky
adb shell pm uninstall --user 0 com.android.providers.partnerbookmarks
adb shell pm uninstall --user 0 com.android.sharedstoragebackup
adb shell pm uninstall --user 0 com.android.wallpapercropper
adb shell pm uninstall --user 0 com.samsung.android.app.watchmanagerstub
adb shell pm uninstall --user 0 com.sec.bcservice
adb shell pm uninstall --user 0 com.tmobile.pr.adapt
adb shell pm uninstall --user 0 com.monotype.android.font.cooljazz
adb shell pm uninstall --user 0 com.sec.factory
adb shell pm uninstall --user 0 com.samsung.android.email.provider
adb shell pm uninstall --user 0 com.sec.epdgtestapp
adb shell pm uninstall --user 0 com.facebook.system
adb shell pm uninstall --user 0 com.facebook.appmanager
adb shell pm uninstall --user 0 com.sec.android.widgetapp.easymodecontactswidget
adb shell pm uninstall --user 0 com.sec.android.app.samsungapps
adb shell pm uninstall --user 0 com.sec.android.widgetapp.samsungapps
adb shell pm uninstall --user 0 com.sec.android.service.health
adb shell pm uninstall --user 0 com.samsung.advp.imssettings
adb shell pm uninstall --user 0 com.samsung.android.keyguardwallpaperupdator
adb shell pm uninstall --user 0 com.android.wallpaper.livepicker
adb shell pm uninstall --user 0 com.sec.android.app.magnifier
adb shell pm uninstall --user 0 com.samsung.android.allshare.service.mediashare
adb shell pm uninstall --user 0 com.sec.android.mimage.photoretouching
adb shell pm uninstall --user 0 com.android.dreams.phototable
adb shell pm uninstall --user 0 com.android.printspooler
adb shell pm uninstall --user 0 com.monotype.android.font.rosemary
adb shell pm uninstall --user 0 com.samsung.safetyinformation
adb shell pm uninstall --user 0 com.sec.android.app.billing
adb shell pm uninstall --user 0 com.samsung.android.app.mirrorlink
adb shell pm uninstall --user 0 com.sec.android.app.SecSetupWizard
adb shell pm uninstall --user 0 com.samsung.SMT
adb shell pm uninstall --user 0 com.policydm
adb shell pm uninstall --user 0 com.samsung.android.securitylogagent
adb shell pm uninstall --user 0 com.sec.smartcard.manager
adb shell pm uninstall --user 0 org.simalliance.openmobileapi.service
adb shell pm uninstall --user 0 com.samsung.android.beaconmanager
adb shell pm uninstall --user 0 com.trustonic.tuiservice
adb shell pm uninstall --user 0 com.sec.android.uibcvirtualsoftkey
adb shell pm uninstall --user 0 com.samsung.android.app.talkback
adb shell pm uninstall --user 0 com.samsung.svoice.sync
adb shell pm uninstall --user 0 com.samsung.android.app.withtv
adb shell pm uninstall --user 0 com.samsung.android.widgetapp.yahooedge.finance
adb shell pm uninstall --user 0 com.samsung.android.widgetapp.yahooedge.sport
adb shell pm uninstall --user 0 com.samsung.android.service.peoplestripe
adb shell pm uninstall --user 0 com.samsung.android.game.gamehome
adb shell pm uninstall --user 0 com.samsung.android.game.gametools
adb shell pm uninstall --user 0 com.mobeam.barcodeService
adb shell pm uninstall --user 0 com.sec.location.nsflp2
adb shell pm uninstall --user 0 com.samsung.android.easysetup
adb shell pm uninstall --user 0 com.sec.android.easyonehand
adb shell pm uninstall --user 0 com.diotek.sec.lookup.dictionary
adb shell pm uninstall --user 0 com.sec.android.easyMover.Agent
adb shell pm uninstall --user 0 com.dsi.ant.service.socket
adb shell pm uninstall --user 0 com.dsi.ant.sample.acquirechannels
adb shell pm uninstall --user 0 com.dsi.ant.server
adb shell pm uninstall --user 0 com.samsung.android.hmt.vrsvc
adb shell pm uninstall --user 0 com.android.chrome
adb shell pm uninstall --user 0 com.google.android.tts
adb shell pm uninstall --user 0 com.samsung.android.samsungpass
adb shell pm uninstall --user 0 com.samsung.android.scloud
adb shell pm uninstall --user 0 com.samsung.android.spayfw
adb shell pm uninstall --user 0 com.samsung.android.svoice
adb shell pm uninstall --user 0 com.samsung.android.mateagent
adb shell pm uninstall --user 0 com.android.egg
adb shell pm uninstall --user 0 com.samsung.android.svoiceime
adb shell pm uninstall --user 0 com.samsung.android.themestore
adb shell pm uninstall --user 0 com.samsung.android.app.simplesharing
adb shell pm uninstall --user 0 com.wsomacp
adb shell pm uninstall --user 0 com.sec.android.cover.ledcover
adb shell pm uninstall --user 0 com.samsung.android.app.ledcoverdream
adb shell pm uninstall --user 0 com.sec.android.app.desktoplauncher
adb shell pm uninstall --user 0 com.sec.android.desktopmode.uiservice
adb shell pm uninstall --user 0 com.samsung.knox.securefolder
adb shell pm uninstall --user 0 com.samsung.android.smartmirroring
adb shell pm uninstall --user 0 com.yelp.android.samsungedge
adb shell pm uninstall --user 0 com.cnn.mobile.android.phone.edgepanel
adb shell pm uninstall --user 0 com.samsung.android.knox.containeragent
adb shell pm uninstall --user 0 com.samsung.android.samsungpassautofill
adb shell pm uninstall --user 0 com.samsung.android.da.daagent
adb shell pm uninstall --user 0 com.android.emergency
adb shell pm uninstall --user 0 com.sec.android.emergencymode.service
adb shell pm uninstall --user 0 com.google.vr.vrcore
adb shell pm uninstall --user 0 com.hancom.office.editor.hidden
adb shell pm uninstall --user 0 com.enhance.gameservice
adb shell pm uninstall --user 0 com.dsi.ant.plugins.antplus
adb shell pm uninstall --user 0 com.tmobile.services.nameid
adb shell pm uninstall --user 0 com.samsung.tmovvm
adb shell pm uninstall --user 0 com.google.android.printservice.recommendation
adb shell pm uninstall --user 0 com.android.managedprovisioning
adb shell pm uninstall --user 0 com.sec.spp.push
adb shell pm uninstall --user 0 com.sec.android.app.camera.avatarauth
adb shell pm uninstall --user 0 com.samsung.android.app.taskedge
adb shell pm uninstall --user 0 com.samsung.android.app.clipboardedge
adb shell pm uninstall --user 0 com.samsung.android.app.assistantmenu
adb shell pm uninstall --user 0 com.sec.android.app.DataCreate
adb shell pm uninstall --user 0 com.android.proxyhandler
adb shell pm uninstall --user 0 com.qualcomm.atfwd
adb shell pm uninstall --user 0 com.qualcomm.timeservice
adb shell pm uninstall --user 0 com.android.dreams.basic
adb shell pm uninstall --user 0 com.samsung.android.mdm
adb shell pm uninstall --user 0 com.sec.android.app.quicktool
adb shell pm uninstall --user 0 com.samsung.android.app.sbrowseredge
adb shell pm uninstall --user 0 com.sec.android.provider.emergencymode
adb shell pm uninstall --user 0 com.sec.enterprise.mdm.services.simpin
adb shell pm uninstall --user 0 com.sec.enterprise.mdm.vpn
adb shell pm uninstall --user 0 com.android.bookmarkprovider
adb shell pm uninstall --user 0 com.sec.android.wallpapercropper2
adb shell pm uninstall --user 0 com.facebook.katana
adb shell pm uninstall --user 0 com.samsung.android.bbc.fileprovider
adb shell pm uninstall --user 0 com.android.mms.service
adb shell pm uninstall --user 0 com.sec.app.push
adb shell pm uninstall --user 0 com.samsung.android.allshare.servicefileshare
adb shell pm uninstall --user 0 com.samsung.android.fmm
adb shell pm uninstall --user 0 com.samsung.android.sdk.professionalaudio.utility.jammonitor
adb shell pm uninstall --user 0 com.samsung.android.fast
