#!/bin/sh
# Please read the documentation before any progres
adb shell pm uninstall --user 0 com.vivo.browser
adb shell pm uninstall --user 0 com.vivo.weather.provider
adb shell pm uninstall --user 0 com.vivo.gametrain
adb shell pm uninstall --user 0 com.nt36xxxtouchscreen.deltadiff
adb shell pm uninstall --user 0 com.vivo.appstore
adb shell pm uninstall --user 0 com.bbk.cloud
adb shell pm uninstall --user 0 com.android.dialer
adb shell pm uninstall --user 0 com.vivo.website
adb shell pm uninstall --user 0 com.bbk.launcher2
adb shell pm uninstall --user 0 com.vivo.livewallpaper.silk
adb shell pm uninstall --user 0 com.facebook.appmanager
adb shell pm uninstall --user 0 com.vivo.livewallpaper.coffeetime
adb shell pm uninstall --user 0 com.vlife.vivo.wallpaper
adb shell pm uninstall --user 0 com.android.BBKClock
adb shell pm uninstall --user 0 com.bbk.photoframewidget
adb shell pm uninstall --user 0 com.android.filemanager
adb shell pm uninstall --user 0 com.vivo.globalsearch
adb shell pm uninstall --user 0 com.bbk.calendar
adb shell pm uninstall --user 0 com.android.contacts
adb shell pm uninstall --user 0 com.android.skintwo
adb shell pm uninstall --user 0 com.vivo.gallery
adb shell pm uninstall --user 0 com.vivo.secime.service
adb shell pm uninstall --user 0 com.android.skinfive
adb shell pm uninstall --user 0 com.android.BBKPhoneInstructions
adb shell pm uninstall --user 0 com.android.notes
adb shell pm uninstall --user 0 com.iqoo.secure
adb shell pm uninstall --user 0 com.bbk.theme.resources
adb shell pm uninstall --user 0 com.vivo.livewallpaper.floatingcloud
adb shell pm uninstall --user 0 com.android.chrome
adb shell pm uninstall --user 0 com.android.skinthree
adb shell pm uninstall --user 0 com.facebook.services
adb shell pm uninstall --user 0 com.android.bookmarkprovider
adb shell pm uninstall --user 0 com.bbk.account
adb shell pm uninstall --user 0 com.google.android.youtube
adb shell pm uninstall --user 0 com.vivo.dream.clock
adb shell pm uninstall --user 0 com.vivo.compass
adb shell pm uninstall --user 0 com.vivo.dream.weather
adb shell pm uninstall --user 0 com.vivo.livewallpaper.coralsea
adb shell pm uninstall --user 0 com.bbk.scene.indoor
adb shell pm uninstall --user 0 com.google.android.videos
adb shell pm uninstall --user 0 com.google.android.googlequicksearchbox
adb shell pm uninstall --user 0 com.android.bbkmusic
adb shell pm uninstall --user 0 com.google.android.marvin.talkback
adb shell pm uninstall --user 0 com.android.BBKTools
adb shell pm uninstall --user 0 com.vivo.collage
adb shell pm uninstall --user 0 com.vivo.widget.calendar
adb shell pm uninstall --user 0 com.android.browser
adb shell pm uninstall --user 0 com.android.skin
adb shell pm uninstall --user 0 com.vivo.weather
adb shell pm uninstall --user 0 com.facebook.system
adb shell pm uninstall --user 0 com.vivo.dream.music
adb shell pm uninstall --user 0 com.vivo.easyshare
adb shell pm uninstall --user 0 com.vivo.doubletimezoneclock
adb shell pm uninstall --user 0 com.bbk.theme
adb shell pm uninstall --user 0 com.vivo.hiboard
adb shell pm uninstall --user 0 com.google.android.gm
adb shell pm uninstall --user 0 com.android.bbksoundrecorder
adb shell pm uninstall --user 0 com.mediatek.mtklogger
adb shell pm uninstall --user 0 com.vivo.email
adb shell pm uninstall --user 0 com.google.android.feedback
adb shell pm uninstall --user 0 com.bbk.iqoo.logsystem
adb shell pm uninstall --user 0 com.trustonic.teeservice
adb shell pm uninstall --user 0 com.vivo.FMRadio
adb shell pm uninstall --user 0 com.vivo.assistant
adb shell pm uninstall --user 0 com.vivo.floatingball
adb shell pm uninstall --user 0 com.android.BBKCrontab
adb shell pm uninstall --user 0 com.vivo.gamecube
adb shell pm uninstall --user 0 com.vivo.shortcutcenter
adb shell pm uninstall --user 0 com.vivo.contentcatcher
adb shell pm uninstall --user 0 com.vivo.gamewatch
adb shell pm uninstall --user 0 com.vivo.agent
adb shell pm uninstall --user 0 com.android.bbklog
adb shell pm uninstall --user 0 com.vivo.fuelsummary
adb shell pm uninstall --user 0 com.vivo.abe
adb shell pm uninstall --user 0 com.android.DemoVideo

# Use the restore script to restore all factory apps from /system
